version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "15:00"
  groups:
    python-packages:
      patterns:
        - "*"
  ignore:
    # Let's keep Django at 4.2 until a new LTS comes along
    - dependency-name: "django"
      versions:
      - ">=5.0"

    # django-tailwind 3.7 and are broken on Python 3.9: https://github.com/timonweb/django-tailwind/issues/210
    - dependency-name: "django-tailwind"
      versions:
      - ">3.6"
